# Generated by Django 4.2.3 on 2023-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
